version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  data_importer:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example_password@mongodb:27017/admin
      CITY_INSPECTIONS_URL: https://github.com/ozlerhakan/mongodb-json-files/raw/refs/heads/master/datasets/city_inspections.json
      COMPANIES_URL: https://github.com/ozlerhakan/mongodb-json-files/raw/refs/heads/master/datasets/companies.json

volumes:
  mongodb_data:
